### ISSUE TITLE
can it work (or be made to work) with input iterators?

### ISSUE THREAD

**Issue by timotheecour** [alehander42/zero-functional#20]
eg:
```nim
  iterator infinite(): int {.closure.} =
    var i = 0
    while true:
      writelnL "ok1"
      yield i
      inc i

let a = infinite-->
           map(it*2).
           take(10)
```

**Comment by michael72** [comment]
Hi - OK - first I'll have to correct your code - and then it's not working anyway. You're right!
(using `-->` and then directly `.` is not a valid syntax)

So something like this would work (at the moment):
```nim
 let a = (0..100) --> map(it*2).
                      sub(0,10)
```

Creates `@[0,...,18]`
- so `sub(0,10)` with 10 being exclusive is used instead of take
Unfortunately the loop does not use `break` so it would run forever.

I could add the following
- dedicated `take` -> uses `sub` (which internally uses `filter`)
- check in `filter` for an end condition (like idx < or idx <= something) and change generated code to something like `if not (idx < something): break`

**Comment by michael72** [comment]
... or better introduce an `until(cond)` function that - internally - calls break when the given condition is `true` -> rewrite `sub` to use `until(idx >= end)` - and `take` uses `until` as well. `filter` itself should maybe not be changed.

**Comment by michael72** [comment]
@timotheecour with #22 it is now possible to create own inline iterators with `--> iter(myIterName)` - they are not as fancy as closure iterators and cannot be moved around to other functions, but they are efficient.

Also with the additions of take, drop and enhancements of sub that have already been merged to master, could we close this issue now?
